### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by Arachnid** [revtel/react-native-nfc-rewriter#21]
Could you please add a LICENSE? It's not clear if this is licensed under the APL like the library, or something different.

**Comment by whitedogg13** [comment]
@Arachnid thanks for spotting this! The APL license has been included.

**Comment by Arachnid** [comment]
Would you consider a more liberal option? As it's example code, it'd be great to be able to use this as a starting point for an app that uses your library, without having to license our own apps indefinitely under APL.

**Comment by whitedogg13** [comment]
Sure! Let's make it MIT!
