### ISSUE TITLE
Can't share the NDEF record sometime

### ISSUE THREAD

**Issue by srluo** [revtel/react-native-nfc-rewriter#23]
Can't share the NDEF record, if the URL has "?"(I guess) in there.
ex. https://sl.revtel.app/?id=comfy

com.revteltech.nfcopenrewriter://share?data=%7B%22name%22:%22WR-Revtel.app%22,%22payload%22:%7B%22tech%22:%22Ndef%22,%22tnf%22:1,%22value%22:%7B%22value%22:%22sl.revtel.app/?id=comfy%22,%22prefix%22:%22https://%22%7D,%22rtd%22:%22U%22%7D%7D

**Comment by whitedogg13** [comment]
fixed, please check the latest v0.0.24
