### ISSUE TITLE
hi Revtel

### ISSUE THREAD

**Issue by gospod1978** [revtel/react-native-nfc-rewriter#4]
i just download this code and start to see how it's work.
I tried to read my Id card but always have error NFCError: 200.
I tried most of your code but the same NFCError:200 
i using iPhone XR.
Can you help how to start read identity card Nationality.
I don't change nothing for your code.
made npm install
pod install
and whit xCode add the developer team.
No error when i build.
Some suggestion?
Thank you

**Comment by smalesevic** [comment]
Is it possible to do this without being enrolled in the Apple Developer Program? I'm only using XCode linked to my Apple ID and getting provisioning profile error as well as no support for the Near Field Communication Tag Reading capability.

**Comment by whitedogg13** [comment]
Hi @smalesevic No. You will have to enroll the Apple Developer Program. Otherwise, you can only run it in simulator, but simulator has no NFC support.

**Comment by whitedogg13** [comment]
Hi @gospod1978 sorry for the late response, not all the RFID cards are supported by core NFC, normally for people new to this domain, I will suggest you to buy some cheap tags in Amazon, such as [NTAG215 by NXP](https://www.amazon.com/dp/B015UMPVNI/ref=sr_1_3_sspa?dchild=1&keywords=nfc+tag&qid=1615418999&sr=8-3-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUE4R0o2MzQ1VVJFTkImZW5jcnlwdGVkSWQ9QTA0OTQzMjQyRTFINUQzTlUzVVBLJmVuY3J5cHRlZEFkSWQ9QTAxOTMyNDFKUEIwUlZDSExBT08md2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl)

**Comment by PaLaMuNDeR** [comment]
> Hi @smalesevic No. You will have to enroll the Apple Developer Program. Otherwise, you can only run it in simulator, but simulator has no NFC support.

@whitedogg13 yet when running in the iOS simulator it just freezes on the splash screen. Is there some other setting that needs to be done to even see the menu on iOS Simulator? There are some warning logs about requirement cycles, but no errors

```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

<img width="338" alt="Screenshot 2021-06-09 at 10 59 40 AM" src="https://user-images.githubusercontent.com/5254663/121334702-ce6fea00-c911-11eb-8b59-5675e665feb9.png">

**Comment by whitedogg13** [comment]
Hi, this is expected. The app performs a NFC feature detection on HomeScreen, and only show buttons when the target device supports NFC.
