### ISSUE TITLE
can we share some data between 2 devices using this library ?

### ISSUE THREAD

**Issue by amitbravo** [revtel/react-native-nfc-rewriter#6]
I need to make an app sharing a url in between 2 devices having the app , can we share some data between 2 devices using this library ?

**Comment by spsingh559** [comment]
I am also looking for similar functionality where I can pass text data from one android phone to other via react native app.

My use case is to send a personal identifiable information data from one app to other in different mobile phones with NFC enabled.  It would be great to see if any peer-to-peer data sharing using NFC example is there.

**Comment by whitedogg13** [comment]
Hi @amitbravo @spsingh559 currently iOS doesn't support p2p NFC. For Android, it had been supported for a while but recently been deprecated. So sadly this is no good way to achieve this.

For now, one possible way is to use Android HCE (Host-based Card Emulation) API. But iOS doesn't support HCE.

**Comment by spsingh559** [comment]
@whitedogg13 thanks for your prompt response. It would be great if you could update the same in read me file of react-native-nfc-manager code base so that many people who may be curious about p2p NFC can directly explore Android HCE (Host-based Card Emulation) API.  I also found a react-native version of HCE https://github.com/appidea/react-native-hce.

**Comment by whitedogg13** [comment]
@spsingh559 thanks for the advice, I will update the readme there.

**Comment by Ajinkya-ulis** [comment]
How I can check devices support devices or not & how I can check devices NFC is already on

**Comment by whitedogg13** [comment]
Hi @Ajinkya-ulis you can use `isSupported()` and `isEnabled()` API from `react-native-nfc-manager`
